export declare function esc(value: unknown): string;
export declare function field(opts?: Record<string, unknown>): string;
export declare function input(opts?: Record<string, unknown>): string;
export declare function textarea(opts?: Record<string, unknown>): string;
export declare function select(opts?: Record<string, unknown>): string;
export declare function numericValue(opts?: Record<string, unknown>): string;
export declare function deltaValue(opts?: Record<string, unknown>): string;
export declare function filterBar(opts?: Record<string, unknown>): string;
export declare function initFilterBar(host: Element, opts?: Record<string, unknown>): { update: (opts: Record<string, unknown>) => void; destroy: () => void };
export declare function segmentedNextIndex(key: string, index: number, length: number): number | null;
export declare function icon(name: string, className?: string): string;
export declare function snippet(opts?: Record<string, unknown>): string;
export declare function button(opts?: Record<string, unknown>): string;
export declare function badge(label: string, variant?: string): string;
export declare const calloutIcons: Record<'neutral' | 'info' | 'success' | 'warn' | 'danger', string>;
export declare function callout(opts?: Record<string, unknown>): string;
export declare function card(opts?: Record<string, unknown>): string;
export declare function pagination(opts?: Record<string, unknown>): string;
export declare function drawerSection(opts?: Record<string, unknown>): string;
export declare function drawer(opts?: Record<string, unknown>): string;
export declare function dropdown(opts?: Record<string, unknown>): string;
export declare function wireDropdown(root?: Document | Element): void;
/** The kit's own match, asked rather than re-implemented by <Dropdown>. */
export declare function dropdownMatch(label: unknown, query: unknown): boolean;
export declare function dropdownFiltering(query: unknown): boolean;
export declare function backLink(opts?: Record<string, unknown>): string;
export declare function statBand(opts?: Record<string, unknown>): string;
export declare function commandPalette(opts?: Record<string, unknown>): string;
export declare function rankGroups<G>(groups: readonly G[], query: string): G[];
export declare function rankCommands<I>(items: readonly I[], query: string): I[];
export declare function scoreCommand(item: Record<string, unknown>, query: string): number;
export declare function paletteHotkey(platform?: string): string;
export declare const PAGE_SIZES: number[];
export declare const DEFAULT_PAGE_SIZE: number;
export type NumericValueOptions = { value?: string | number | null; unit?: string; missing?: string };
export type DeltaValueOptions = { value?: string | null; tone?: 'success' | 'danger' | 'neutral'; basisId?: string; missing?: string };
export declare function formatNumericValue(options?: NumericValueOptions): { text: string; unit: string; missing: string | undefined };
export declare function formatDeltaValue(options?: DeltaValueOptions): { text: string; className: string; basisId: string | undefined };
export declare const SCORE: Record<'exact' | 'prefix' | 'wordStart' | 'contains' | 'keyword' | 'description' | 'subsequence', number>;
export declare const iconNames: string[];
export declare const iconCategories: { name: string; names: string[] }[];
export declare const iconOnlyAllowed: Record<string, string>;
export declare const iconMeanings: Record<string, string>;
export declare const sun: string;
export declare const moon: string;
export declare function prism(prefix?: string, size?: number): string;
export declare function seedling(prefix?: string, size?: number): string;
export declare function brand(options?: { p?: string; word?: string; size?: number; href?: string }): string;
export declare function illo(name: string): string;
export * from './motion.js';
export declare const illoNames: string[];
