export const TITLE = 'Dense tables';
export const BLURB = 'Keep numbers comparable when the dataset needs many rows and columns.';
export const RULES = [
  { id: 'surface', imperative: 'Put tables on a white surface in light mode.', why: 'Grey or tinted table backgrounds make dense rows harder to separate from the surrounding interface. Dark mode uses the base canvas. Zebra and hover do not add a grey fill; the row edge marks hover.', kit: [{ ref: 'src/styles/table.css:88', pattern: '.ui-table { background: var(--table-bg);' }] },
  { id: 'density', imperative: 'Choose density without shrinking the type.', why: 'Dense keeps the existing spacing; compact uses tighter vertical padding and a 33px minimum row. Content and larger font tokens can grow either row. Keep readable values at the small text rank and unit suffixes at the extra-small rank.' },
  { id: 'numbers', imperative: 'Right-align numeric headers and values.', why: 'Tabular numerals and a shared edge let a reader compare magnitudes. Keep text left-aligned and sort by raw values rather than formatted strings.' },
  { id: 'delta', imperative: 'Print the sign and name the comparison.', why: 'A plus or minus carries direction without colour. The caller chooses whether a change is good or bad; a cost increase need not be green. Zero is neutral, and a missing comparison says so instead of claiming zero.' },
  { id: 'units', imperative: 'Keep units smaller and in body ink.', why: 'USD, M, B and percent signs carry information. They do not qualify as muted glyphs or empty placeholders. Put a shared unit in the column heading when possible and explain abbreviations in reachable text.' },
  { id: 'overflow', imperative: 'Scroll columns instead of squeezing them.', why: 'There is no universal column-count limit. Keep a sticky header and a pinned identity column inside a named keyboard-focusable scroll region. On narrow screens, the identity contracts to its symbol; its full name remains in the accessible name and can be reached through its company link. Never silently remove data columns.' },
  { id: 'states', imperative: 'Keep the table stable while results update.', why: 'Retain rows while refreshing and report busy state. Distinguish no data, no matches and an error; offer clearing filters or retrying. Preserve focus when removing a filter and keep all views over the same dataset.' },
];
